# Image Scrapper

from icrawler.builtin import GoogleImageCrawler
import os

ingredients = [
    "canned pineapple slices",
    "canned peaches",
    "dried cranberries",
    "raisins",
    "frozen strawberries",
    "frozen blueberries",
    "canned diced tomatoes",
    "canned corn",
    "canned green beans",
    "canned mushrooms",
    "frozen broccoli florets",
    "frozen spinach",
    "jarred roasted red peppers",
    "canned artichoke hearts",
    "canned olives",
    "carton of milk",
    "block of cheddar cheese",
    "shredded mozzarella cheese",
    "parmesan cheese wedge",
    "carton of heavy cream",
    "tub of cream cheese",
    "carton of sour cream",
    "yogurt cups",
    "butter sticks",
    "frozen chicken breasts",
    "packaged ground beef",
    "vacuum-sealed bacon",
    "packaged sausages",
    "canned tuna",
    "canned salmon",
    "frozen shrimp",
    "vacuum-sealed tofu",
    "box of white rice",
    "box of brown rice",
    "bag of basmati rice",
    "box of pasta",
    "box of spaghetti",
    "box of lasagna sheets",
    "bag of flour tortillas",
    "loaf of sliced bread",
    "bag of all-purpose flour",
    "bag of whole wheat flour",
    "container of oatmeal",
    "box of instant mashed potatoes",
    "box of cornstarch",
    "canned black beans",
    "canned kidney beans",
    "canned chickpeas",
    "bag of lentils",
    "ketchup bottle",
    "mustard bottle",
    "jar of mayonnaise",
    "bottle of soy sauce",
    "bottle of Worcestershire sauce",
    "jar of peanut butter",
    "jar of grape jelly",
    "jar of honey",
    "jar of maple syrup",
    "jar of marinara sauce",
    "bottle of barbecue sauce",
    "bottle of hot sauce",
    "bag of granulated sugar",
    "bag of brown sugar",
    "box of baking powder",
    "box of baking soda",
    "bottle of vanilla extract",
    "box of cocoa powder",
    "bag of chocolate chips",
    "bottle of olive oil",
    "bottle of vegetable oil",
    "bottle of coconut oil",
    "stick of shortening",
    "salt shaker",
    "ground black pepper",
    "ground cinnamon",
    "ground paprika",
    "garlic powder",
    "onion powder",
    "dried oregano",
    "dried basil",
    "ground chili powder",
    "dried parsley flakes",
    "box of crackers",
    "bag of potato chips",
    "box of microwave popcorn",
    "box of tea bags",
    "can of coffee grounds",
    "bottle of orange juice",
    "bottle of soda",
    "frozen pizza",
    "box of chicken nuggets",
    "bag of frozen French fries",
    "carton of ice cream",
    "bottle of white vinegar",
    "bottle of apple cider vinegar",
    "jar of pickles",
    "jar of relish",
    "carton of soy milk",
    "carton of almond milk",
    "gallon of milk",
    "vacuum-sealed chicken breasts",
    "vacuum-sealed chicken thighs",
    "packaged ground turkey",
    "pre-cooked bacon strips",
    "vacuum-sealed pork chops",
    "packaged hot dogs",
    "packaged beef sausages",
    "packaged Italian sausages",
    "packaged deli turkey slices",
    "packaged ham slices",
    "packaged salami slices",
    "frozen salmon filets",
    "frozen cod filets",
    "box of penne",
    "box of fusilli",
    "box of linguine",
    "box of fettuccine",
    "box of rigatoni",
    "box of macaroni",
    "box of orzo",
    "box of rotini",
    "package of ravioli",
    "package of tortellini",
    "cumin powder",
    "ground turmeric",
    "ground nutmeg",
    "curry powder",
    "smoked paprika",
    "cayenne pepper",
    "Italian seasoning",
    "ground ginger",
    "red pepper flakes",
    "steak seasoning",
    "jar of alfredo sauce",
    "jar of pesto",
    "bottle of teriyaki sauce",
    "jar of salsa",
    "jar of hoisin sauce",
    "bottle of fish sauce",
    "bottle of oyster sauce",
    "jar of tahini",
    "bottle of chili garlic sauce",
    "bottle of sriracha",
    "jar of pizza sauce",
    "loaf of white bread",
    "loaf of whole wheat bread",
    "loaf of sourdough bread",
    "packaged bagels",
    "packaged English muffins",
    "packaged hot dog buns",
    "packaged hamburger buns",
    "packaged pita bread",
    "packaged tortillas",
    "packaged naan bread",
    "packaged brioche buns",
    "packaged sandwich rolls",
    "bag of jasmine rice",
    "box of quinoa",
    "bag of couscous",
    "bag of barley",
    "bag of farro",
    "box of wild rice",
    "bag of bulgur wheat",
    "bag of millet",
    "bag of freekeh",
    "box of cereal",
    "box of oatmeal packets",
    "box of granola bars",
    "bag of tortilla chips",
    "jar of almond butter",
    "can of sweetened condensed milk",
    "carton of chicken broth",
    "carton of vegetable broth",
    "box of powdered milk",
    "box of stuffing mix",
    "bottle of balsamic vinegar",
    "carton of oat milk"
]

output_dir = "dataset_package/images"  # structure compatible with YOLO
images_per_class = 500

# Base directory
os.makedirs(output_dir, exist_ok=True)

# Scrapper
for ingredient in ingredients:
    class_dir = os.path.join(output_dir, ingredient.replace(" ", "_"))
    os.makedirs(class_dir, exist_ok=True)

    crawler = GoogleImageCrawler(storage={"root_dir": class_dir})
    crawler.crawl(keyword=ingredient, max_num=images_per_class)

print("Image scraping completed.")
